services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    entrypoint:
      - /start.sh
    command:
      - serve
    environment:
      TZ: Etc/UTC
      ADMINS: admin
      USERS: user1,user2

      NTFY_BASE_URL: https://example.com
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true

    volumes:
      - ./ntfy:/var/lib/ntfy
      - ./start.sh:/start.sh
      #- /cache/ntfy:/var/cache/ntfy
      #- /ntfy:/etc/ntfy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 30M
        reservations:
          cpus: '0.0001'
          memory: 20M